### ISSUE TITLE
bug(client): inherited with_* helpers cannot reconstruct KatanaClient

### ISSUE THREAD

**Issue by dougborg** [dougborg/katana-openapi-client#1084]
Reproduced locally on main at 1bc6e30e while investigating #601, without network requests:

```python
from katana_public_api_client import KatanaClient

KatanaClient(api_key="test-key", base_url="https://example.test/v1").with_headers(
    headers={"X-Custom": "value"}
)
```

The inherited generated `AuthenticatedClient.with_headers` calls `attrs.evolve(self, ...)`. This reconstructs the `KatanaClient` subclass using generated-client constructor fields such as `raise_on_unexpected_status`, `httpx_args`, and `verify_ssl`. Its custom constructor treats these as transport kwargs, leading to `TypeError: AsyncHTTPTransport.__init__() got an unexpected keyword argument 'raise_on_unexpected_status'`.

This is independent of the synchronous transport failure in #601. Audit the other inherited `with_*` helpers for the same reconstruction mismatch.

Acceptance:

- `with_headers`, `with_cookies`, and `with_timeout` work on `KatanaClient` with explicit preservation of subclass configuration and lifecycle semantics.
- Cover initialized and uninitialized HTTP clients, without leaking or prematurely closing shared transports.
- Keep generated client code generated; fix the handwritten subclass or generation customization.
